baseURL : "https://blog.rex-tsou.com"
languageCode : "en"
theme: "clean"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
author: "Rex Tsou"
title : "為了可能的聲音"
hasCJKLanguage: true
enableEmoji: true
disqusshortname: "akccakcctw"
googleAnalytics: "UA-57924156-2"
MetaDataFormat: "yaml"

taxonomies:
  category: "categories"
  tag: "tags"

permalinks:
  post: "/:year/:month/:title/"

params:
  author: "Rex Tsou"
  copyright: '© 2018 <a href="https://github.com/akccakcctw" target="_blank">Rex Tsou</a>'
  title: "為了可能的聲音"
  description: "為了可能的聲音"
  ogType: "article"
  keywords:
    - programming
    - thinking
    - writing
  social:
    - url: "https://github.com/akccakcctw"
      fa_icon: "fa-github"
    - url: "https://www.facebook.com/akccakcctw"
      fa_icon: "fa-facebook-square"
    - url: "/index.xml"
      fa_icon: "fa-rss"
